import type { Metadata } from 'next'
import './globals.css'
import SessionProvider from '@/app/components/SessionProvider'
import { getServerSession } from 'next-auth'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Next-Auth Project',
  description: 'Generated by SamuDev hands'
}

export default async function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
